/* Generated by cbindgen — do not edit manually */

#ifndef HEXA_TUNE_PROTO_H
#define HEXA_TUNE_PROTO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A byte slice descriptor for FFI (pointer + length).
 */
typedef struct HtpSlice {
  /**
   * Pointer to the data.
   */
  const uint8_t *ptr;
  /**
   * Length of the data.
   */
  uintptr_t len;
} HtpSlice;

/**
 * Parse result returned by `htp_at_parse`.
 */
typedef struct HtpAtParseResult {
  /**
   * Parsed command ID.
   */
  uint32_t id;
  /**
   * Operation type: 0=Set, 1=Query, 2=Response.
   */
  int32_t op;
  /**
   * Offset of command name within the input buffer.
   */
  uintptr_t name_offset;
  /**
   * Length of command name.
   */
  uintptr_t name_len;
  /**
   * Number of parameters (max 8).
   */
  uintptr_t param_count;
  /**
   * Offsets of each parameter within the input buffer.
   */
  uintptr_t param_offsets[8];
  /**
   * Lengths of each parameter.
   */
  uintptr_t param_lens[8];
} HtpAtParseResult;

/**
 * Encodes an AT command string into the output buffer.
 *
 * # Safety
 * All pointers must be valid for their respective lengths.
 */
int32_t htp_at_encode(const uint8_t *name_ptr,
                      uintptr_t name_len,
                      uint32_t id,
                      int32_t op,
                      const struct HtpSlice *params_ptr,
                      uintptr_t params_count,
                      uint8_t *out_ptr,
                      uintptr_t out_cap,
                      uintptr_t *out_len);

/**
 * Parses an AT command from a byte buffer.
 *
 * On success, populates the `HtpAtParseResult` struct with offsets into the input buffer.
 *
 * # Safety
 * All pointers must be valid.
 */
int32_t htp_at_parse(const uint8_t *input_ptr,
                     uintptr_t input_len,
                     struct HtpAtParseResult *result);

/**
 * Frames payload bytes into a SysEx message.
 *
 * # Safety
 * All pointers must be valid for their respective lengths.
 */
int32_t htp_sysex_frame(const uint8_t *payload_ptr,
                        uintptr_t payload_len,
                        uint8_t *out_ptr,
                        uintptr_t out_cap,
                        uintptr_t *out_len);

/**
 * Extracts payload from a SysEx message.
 *
 * # Safety
 * All pointers must be valid.
 */
int32_t htp_sysex_unframe(const uint8_t *data_ptr,
                          uintptr_t data_len,
                          uintptr_t *out_offset,
                          uintptr_t *out_len);

/**
 * Converts SysEx bytes to USB MIDI 4-byte packets.
 *
 * # Safety
 * All pointers must be valid for their respective lengths.
 */
int32_t htp_usb_packetize(const uint8_t *sysex_ptr,
                          uintptr_t sysex_len,
                          uint8_t (*out_ptr)[4],
                          uintptr_t out_cap,
                          uintptr_t *out_count);

/**
 * Reassembles SysEx bytes from USB MIDI 4-byte packets.
 *
 * # Safety
 * All pointers must be valid for their respective lengths.
 */
int32_t htp_usb_depacketize(const uint8_t (*packets_ptr)[4],
                            uintptr_t packet_count,
                            uint8_t *out_ptr,
                            uintptr_t out_cap,
                            uintptr_t *out_len);

/**
 * Full pipeline: encode AT command → SysEx → USB MIDI packets.
 *
 * # Safety
 * All pointers must be valid for their respective lengths.
 */
int32_t htp_encode_to_packets(const uint8_t *name_ptr,
                              uintptr_t name_len,
                              uint32_t id,
                              int32_t op,
                              const struct HtpSlice *params_ptr,
                              uintptr_t params_count,
                              uint8_t *at_buf_ptr,
                              uintptr_t at_buf_cap,
                              uint8_t *sysex_buf_ptr,
                              uintptr_t sysex_buf_cap,
                              uint8_t (*packets_out_ptr)[4],
                              uintptr_t packets_out_cap,
                              uintptr_t *packets_out_count);

#endif  /* HEXA_TUNE_PROTO_H */
